TRAIN_PROMPTS = [
    "Abs",
    "BinarySearch",
    "BubbleSort",
    "CalDiv",
    "CanyonSearch",
    "Compare",
    "ComputeAvg",
    "ComputeIsEven",
    "CountLessThan",
    "DoubleQuadruple",
    "Find",
    "FindEvenNumbers",
    "IsPalindrome",
    "LinearSearch",
    "LinearSearch3",
    "LongestCommonPrefix",
    "M",
    "Min",
    "MultipleReturns",
    "Quotient",
    "SelectionSort",
    "SetToSeq",
    "SlopeSearch",
    "SquareRoot",
    "Sum",
    "Swap",
    "SwapArithmetic",
    "SwapBitvectors"
]

TEST_PROMPTS = None
